typography_spectrum: 0.11708096717484295
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6571711450815201
  lightness: 0.4183298877906054
  saturation: 0.1391599338967353
  rhythmicContrast: 0.7113595423288643
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8670233823359013
analytics:
  google: null
  facebook: null
  twitter: null
name: Clark.Media
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Clark.Media
description: Change Everything
purpose: []
